### ISSUE TITLE
Admin Pages Layout

### ISSUE THREAD

**Issue by hey-waffles** [lucyawrey/reroll#13]
Hash out the structure for the admin-side pages. Leave placeholders for other developers to build the pages out

**Comment by hey-waffles** [comment]
[Admin Pages documentation](https://github.com/lucyawrey/reroll/wiki/Admin-Page-Layout)

Once this is finalized, I'll be adding more in-depth descriptions for pages so that they can be scoped out for people to make them

**Comment by lucyawrey** [comment]
No longer relevant as we are not creating page layouts ahead of time
